#!/usr/bin/env python3
"""
飞书 (Feishu) 集成配置脚本
自动化配置 Hermes AI 与飞书的集成
"""

import json
import os
import sys
import requests
from pathlib import Path

class FeishuSetup:
    def __init__(self):
        self.hermes_dir = Path.home() / ".hermes"
        self.env_file = self.hermes_dir / ".env"
        self.config_file = self.hermes_dir / "config.yaml"
        
    def check_prerequisites(self):
        """检查前置条件"""
        print("🔍 检查前置条件...")
        
        # 检查 Hermes 是否安装
        try:
            import subprocess
            result = subprocess.run(['hermes', '--version'], capture_output=True, text=True)
            if result.returncode == 0:
                print("✅ Hermes Agent 已安装")
                print(f"   版本: {result.stdout.strip()}")
            else:
                print("❌ Hermes Agent 未正确安装")
                return False
        except FileNotFoundError:
            print("❌ 未找到 Hermes Agent，请先安装")
            print("   安装命令: curl -fsSL https://hermesagent.dev/install.sh | bash")
            return False
        
        # 检查配置目录
        if not self.hermes_dir.exists():
            print("📁 创建 Hermes 配置目录...")
            self.hermes_dir.mkdir(parents=True, exist_ok=True)
        
        return True
    
    def get_feishu_credentials(self):
        """获取飞书应用凭据"""
        print("\n🔑 配置飞书应用凭据")
        print("请访问飞书开放平台创建应用: https://open.feishu.cn/")
        print()
        
        app_id = input("请输入 App ID: ").strip()
        if not app_id:
            print("❌ App ID 不能为空")
            return None
            
        app_secret = input("请输入 App Secret: ").strip()
        if not app_secret:
            print("❌ App Secret 不能为空")
            return None
        
        verification_token = input("请输入 Verification Token: ").strip()
        encrypt_key = input("请输入 Encrypt Key (可选): ").strip()
        
        webhook_url = input("请输入 Webhook URL (例: https://your-domain.com): ").strip()
        if not webhook_url:
            webhook_url = "http://localhost:8000"
        
        return {
            'app_id': app_id,
            'app_secret': app_secret,
            'verification_token': verification_token,
            'encrypt_key': encrypt_key,
            'webhook_url': webhook_url
        }
    
    def test_feishu_connection(self, credentials):
        """测试飞书连接"""
        print("\n🧪 测试飞书连接...")
        
        # 获取 access_token
        token_url = "https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal"
        token_data = {
            "app_id": credentials['app_id'],
            "app_secret": credentials['app_secret']
        }
        
        try:
            response = requests.post(token_url, json=token_data)
            result = response.json()
            
            if result.get('code') == 0:
                print("✅ 飞书 API 连接成功")
                return True
            else:
                print(f"❌ 飞书 API 连接失败: {result.get('msg')}")
                return False
        except Exception as e:
            print(f"❌ 连接测试失败: {e}")
            return False
    
    def update_env_file(self, credentials):
        """更新环境配置文件"""
        print("\n📝 更新环境配置...")
        
        # 读取现有环境变量
        env_vars = {}
        if self.env_file.exists():
            with open(self.env_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_vars[key] = value
        
        # 添加飞书配置
        feishu_config = {
            'FEISHU_APP_ID': credentials['app_id'],
            'FEISHU_APP_SECRET': credentials['app_secret'],
            'FEISHU_VERIFICATION_TOKEN': credentials['verification_token'],
            'FEISHU_WEBHOOK_URL': credentials['webhook_url']
        }
        
        if credentials['encrypt_key']:
            feishu_config['FEISHU_ENCRYPT_KEY'] = credentials['encrypt_key']
        
        # 更新环境变量
        env_vars.update(feishu_config)
        
        # 写入文件
        with open(self.env_file, 'w', encoding='utf-8') as f:
            f.write("# Hermes Agent Environment Variables\n")
            f.write("# Generated by Feishu setup script\n\n")
            
            # 分组写入
            f.write("# === 飞书配置 ===\n")
            for key, value in feishu_config.items():
                f.write(f"{key}={value}\n")
            
            f.write("\n# === 其他配置 ===\n")
            for key, value in env_vars.items():
                if not key.startswith('FEISHU_'):
                    f.write(f"{key}={value}\n")
        
        print(f"✅ 环境配置已保存到: {self.env_file}")
    
    def setup_hermes_config(self):
        """配置 Hermes 主配置文件"""
        print("\n⚙️ 配置 Hermes 主配置...")
        
        # 检查是否需要初始化配置
        try:
            import subprocess
            result = subprocess.run(['hermes', 'config'], capture_output=True, text=True)
            print("✅ Hermes 配置文件已存在")
        except Exception as e:
            print(f"⚠️ 无法读取 Hermes 配置: {e}")
    
    def start_gateway_service(self):
        """启动网关服务"""
        print("\n🚀 配置网关服务...")
        
        try:
            import subprocess
            
            # 检查服务状态
            result = subprocess.run(['hermes', 'gateway', 'status'], 
                                  capture_output=True, text=True)
            
            if "running" in result.stdout.lower():
                print("✅ Gateway 服务已在运行")
                restart = input("是否重启服务以应用新配置? (y/N): ").strip().lower()
                if restart == 'y':
                    subprocess.run(['hermes', 'gateway', 'restart'])
                    print("🔄 服务已重启")
            else:
                print("📦 安装并启动 Gateway 服务...")
                
                # 安装服务
                install_result = subprocess.run(['hermes', 'gateway', 'install'], 
                                             capture_output=True, text=True)
                if install_result.returncode == 0:
                    print("✅ Gateway 服务安装成功")
                else:
                    print(f"⚠️ 服务安装可能有问题: {install_result.stderr}")
                
                # 启动服务
                start_result = subprocess.run(['hermes', 'gateway', 'start'], 
                                           capture_output=True, text=True)
                if start_result.returncode == 0:
                    print("✅ Gateway 服务启动成功")
                else:
                    print(f"❌ 服务启动失败: {start_result.stderr}")
        
        except Exception as e:
            print(f"❌ 服务配置失败: {e}")
            print("请手动运行: hermes gateway setup")
    
    def generate_webhook_info(self, credentials):
        """生成 Webhook 配置信息"""
        print("\n📋 Webhook 配置信息:")
        print("=" * 50)
        
        webhook_url = credentials['webhook_url']
        if not webhook_url.startswith('http'):
            webhook_url = f"https://{webhook_url}"
        
        print(f"📡 Webhook URL: {webhook_url}/webhook/feishu")
        print(f"🔑 Verification Token: {credentials['verification_token']}")
        if credentials['encrypt_key']:
            print(f"🔐 Encrypt Key: {credentials['encrypt_key']}")
        
        print("\n📝 在飞书开放平台中配置:")
        print("1. 进入应用管理 → 事件订阅")
        print(f"2. 请求网址配置: {webhook_url}/webhook/feishu")
        print(f"3. 验证 Token: {credentials['verification_token']}")
        print("4. 订阅事件:")
        print("   - 接收消息 (im.message.receive_v1)")
        print("   - 用户进群 (im.chat.member.user.added_v1)")
        print("   - 用户退群 (im.chat.member.user.withdrawn_v1)")
        
        print("\n🔐 权限配置:")
        print("- 获取与发送单聊、群组消息")
        print("- 以应用身份读取通讯录")
        print("- 获取与上传图片或文件资源")
    
    def run(self):
        """运行完整的设置流程"""
        print("🤖 Hermes AI - 飞书集成配置向导")
        print("=" * 50)
        
        # 检查前置条件
        if not self.check_prerequisites():
            return False
        
        # 获取凭据
        credentials = self.get_feishu_credentials()
        if not credentials:
            return False
        
        # 测试连接
        if not self.test_feishu_connection(credentials):
            retry = input("连接测试失败，是否继续配置? (y/N): ").strip().lower()
            if retry != 'y':
                return False
        
        # 更新配置
        self.update_env_file(credentials)
        self.setup_hermes_config()
        
        # 启动服务
        self.start_gateway_service()
        
        # 显示配置信息
        self.generate_webhook_info(credentials)
        
        print("\n🎉 飞书集成配置完成!")
        print("现在您可以:")
        print("1. 在飞书中添加您的机器人应用")
        print("2. 向机器人发送消息测试功能")
        print("3. 使用 'hermes gateway status' 检查服务状态")
        
        return True

def main():
    setup = FeishuSetup()
    
    try:
        success = setup.run()
        if success:
            print("\n✅ 设置成功完成!")
        else:
            print("\n❌ 设置过程中出现问题")
            sys.exit(1)
    except KeyboardInterrupt:
        print("\n\n❌ 用户取消设置")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ 意外错误: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()